#!/bin/sh

BASEDIR=$(dirname $0)
APPPATH="$(dirname $(dirname $BASEDIR))"
LOCALDIR="/usr/local/bin"
APPNAME=$(basename "$APPPATH" ".app")
TOOLDIR="/usr/local/AppTool"
EXEPATH="$TOOLDIR/$APPNAME.app/Contents/MacOS"
ALIASNAME="taylor"

# Copy application to /usr/local/AppTool
echo "Copy $ALIASNAME to $TOOLDIR"
rm -rf "$TOOLDIR/$APPNAME.app"
cp -R $APPPATH $TOOLDIR

# Make shortcut from /usr/local/AppTool/Taylor/Contents/MacOS/Taylor to /usr/local/bin
echo "Make $ALIASNAME shortcut to $LOCALDIR"
rm $LOCALDIR/$ALIASNAME
ln -sf "$EXEPATH/$ALIASNAME" "$LOCALDIR"
